trigger:
- master
- pr

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
    customEndpoint: 'ciq'

- script: npm run build
  name: build
  displayName: "Run the build"

- script: npm run makeInstaller:dev
  name: makeInstaller
  displayName: "Make a dev installer"

- script: npm run makeInstaller:prod
  name: makeInstaller
  displayName: "Make a production installer"